syntax on

colorscheme dw_green
set background=dark

set hlsearch
set nu
set autoindent
set ts=4
set sts=4
set cindent
set laststatus=2
set shiftwidth=4
set showmatch
set smartcase
set smarttab
set smartindent
set ruler
set fileencodings=utf8,euc-kr
set encoding=utf-8
set backspace=indent,eol,start
set guifont=굴림체:h14
